workflows:
  android-workflow:
    name: Build Android APK
    max_build_duration: 15
    environment:
      vars:
        PACKAGE_NAME: "com.example.appblocker"
    scripts:
      - name: Build debug APK
        script: |
          cd android && ./gradlew assembleDebug
    artifacts:
      - build/app/outputs/flutter-apk/app-debug.apk